# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2

job_defaults: &job_defaults
  docker:
    - image: 'circleci/node:10.15.3'

cache_key: &cache_key v1-dependencies-deps-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
dist_key: &dist_key v1-dependencies-dist-{{ .Revision }}

jobs:
  install:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Install
          command: yarn install
      - save_cache:
          key: *cache_key
          paths:
            - node_modules

  lintPug:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: lint pug
          command: yarn lint:pug

  lintStylus:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: lint stylus
          command: yarn lint:stylus

  test:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: test
          command: yarn test

  release:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - restore_cache:
          key: *dist_key
      - run:
         name: Semantic release
         command: npm run semantic-release --debug || true

  build-dist:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Build dist
          command: yarn build:dist
      - save_cache:
          key: *dist_key
          paths:
              - dist

  build-docs:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Build dist
          command: yarn build:all
      - save_cache:
          key: *dist_key
          paths:
              - dist

workflows:
  version: 2
  build-test-release:
    jobs:
      - install
      - lintPug:
          requires:
            - install
      - lintStylus:
          requires:
            - install
      - test:
          requires:
            - install
      - build-dist:
          requires:
            - lintPug
            - lintStylus
            - test
      - build-docs:
          requires:
            - lintPug
            - lintStylus
      - release:
          requires:
            - build-docs
            - build-dist
          filters:
            branches:
              only:
                - master

